// // This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
// require('../../js/transition.js')
// require('../../js/alert.js')
// require('../../js/button.js')
// require('../../js/carousel.js')
// require('../../js/collapse.js')
// require('../../js/dropdown.js')
// require('../../js/modal.js')
// require('../../js/tooltip.js')
// require('../../js/popover.js')
// require('../../js/scrollspy.js')
// require('../../js/tab.js')
// require('../../js/affix.js')

// 	$(function(){
// 		 $(".ziliao").click(function(){
// 		 		$(".sousuo").text("项目资料");
		 	
// 		 });
// 	});
	
// getElementById('ziliao').click("")


// $(function(){
// $(.sec-2).hide();
// $("#show").click(function(){
//   $("p").show();
// });
// });


// 	$(function(){
// 		//remove
// 		$("ul li:eq(0)").click(function(){
// 			alert("猫猫！");
// 		});
// 		$("input:eq(0)").click(function(){
// 			var $li= $("ul li:eq(0)").remove();//删除猫猫
// 			$("ul li").remove("li[title=miao]");//删除猫猫
// 			$("input:eq(4)").click(function(){
// 				$li.appendTo("ul");
// 			});
// 		});
// 		//datach
// 		$("ul li:eq(1)").click(function(){
// 			alert("狗狗！");
// 		});
// 		$("input:eq(1)").click(function(){
// 			var $li=$("ul li:eq(1)").detach();
// 			$("input:eq(3)").click(function(){
// 				$li.appendTo("ul");
// 			});
// 		});
// 		$("input:eq(2)").click(function(){
// 			$("ul li:eq(2)").empty();//清除鸟鸟
// 		});
		
// 	});
// 	$(function(){
// 	$(".parent").click(function(){
// 		$(this)
// 		.toggleClass("selected")
// 		.siblings('.child_'+this.id).toggle();
// 	});
// });
// 	